#!/bin/bash

# Example script showing how to use the linear-standup tool

echo "=== Linear Standup Tool - Usage Example ==="
echo ""
echo "1. Make sure you've created a .env file with your API keys:"
echo "   cp .env.example .env"
echo ""
echo "2. Edit .env and add your keys:"
echo "   - LINEAR_API_KEY (from https://linear.app/settings/api)"
echo "   - OPENAI_API_KEY (from https://platform.openai.com/api-keys)"
echo ""
echo "3. Run the tool in development mode:"
echo "   npm run dev"
echo ""
echo "4. Or build and run:"
echo "   npm run build"
echo "   npm start"
echo ""
echo "The tool will:"
echo "  - Fetch your Linear tasks from the last 24 hours"
echo "  - Categorize them (Done, In Review, In Progress)"
echo "  - Generate a friendly standup update using AI"
echo "  - Display text ready to paste into Slack"
echo ""
echo "Configuration options (in .env):"
echo "  - HOURS_LOOKBACK: How many hours to look back (default: 24)"
echo "  - LINEAR_VIEW_URL: Optional link to your Linear view"
echo ""
